### ISSUE TITLE
Move 

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-filepond#9]
I suggest we remove the below config block and maybe just add it to the documentation as an option. Without the full PR these bundled files came from, they currently don't make much sense imo;
- The current situation would 'magically' change filepond requirements behaviour if you happen to have SimplerSilverstripe installed (should be a conscious choice instead). 
- Also the packagist/mix files etc are missing  from this module so there's no way to update these bundles.
- Probably it even makes sense to delete the bundled files alltogether, as they'll also not be updated with any bugfixes etc.

I think the implemented parts of the PR are now more of a burden on your time and not worth the extra effort. I'm thinking to instead publish an filepond-addon module to implement the functionality initially proposed in the PR. That way you can keep your module focused as well.

```YML
---
Name: filepond-simpler
After: "#simpler_silverstripe"
Only:
  moduleexists: "restruct/silverstripe-simpler"
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'lekoala/silverstripe-filepond:javascript/bundle.js'
    - 'lekoala/silverstripe-filepond:javascript/FilePondField.js'
  extra_requirements_css:
    - 'lekoala/silverstripe-filepond:javascript/bundle.css'
LeKoala\FilePond\FilePondField:
  enable_ajax_init: false
```
